rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip", "headers" ]
  static:
    dir: "public"
    forbid: [".php"]
  headers:
    response:
      X-Powered-By: "RoadRunner"

server:
  command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8080"
  env:
    APP_ENV: local
    APP_DEBUG: true
    DB_HOST: mysql
    DB_PORT: 3306

logs:
  mode: production
  level: info
